// src/views/Career.tsx
import Title from "@/components/title/title";
import { Component } from "solid-js";

const Career: Component = () => {
  const data: Array<{
    company: string;
    position: string;
    date: string;
    image: string;
  }> = [
    {
      company: "Mascitra.com",
      position: "Leader Junior Full Stack Developer",
      date: "Dec 2019 - Apr 2020",
      image: "https://mascitra.com/uploads/portofolio/157/full/_K8C1203.jpg",
    },
    {
      company: "Freelance",
      position: "Full Stack Developer",
      date: "Oct 2020 - Now",
      image: "https://miro.medium.com/max/1200/1*BBct14l3of-42X9TjH65QA.png",
    },
  ];

  return (
    <>
      <div class="w-full">
        <Title title="Career" subtitle="The amazing of my experience" />
        <div class="w-full">
          {data.map((item) => (
            <div class="bg-white dark:bg-gray-900 rounded shadow p-4 mb-4 transition hover:(transform scale-105) mb-3">
              <div class="flex md:flex-row flex-col justify-between items-center">
                <div class="md:w-auto w-full">
                  <img
                    class="md:w-400px w-full md:mb-0 mb-8 h-180px bg-gray-100 rounded-md object-cover"
                    src={item.image}
                    alt={item.company}
                  />
                </div>
                <div class="md:pl-5 w-full">
                  <div class="text-3xl font-semibold text-primary">
                    {item.company}
                  </div>
                  <div class="mt-1">{item.position}</div>
                  <div class="mt-1">{item.date}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Career;

// pages/career/index.vue
<script setup lang="ts">
import { careers } from "~/datas/career";

const isOdd = (index: number) => index % 2 === 0;
</script>

<template>
  <SeoMeta title="Career"></SeoMeta>
  <div class="py-10">
    <div class="text-center" data-aos="fade-down">
      <div class="text-4xl font-bold">Career</div>
      <div>Let me share you some of my experience</div>
    </div>
    <div class="mt-20 space-y-10">
      <template v-for="(career, i) in careers">
        <div
          class="flex md:flex-row flex-col md:items-stretch"
          :class="isOdd(i) ? 'md:flex-row-reverse items-start' : 'items-end'"
        >
          <img
            :src="career.image"
            alt=""
            class="md:size-56 sm:size-32 size-24 md:rounded rounded-full object-cover md:mb-0 mb-5"
            :data-aos="isOdd(i) ? 'fade-right' : 'fade-left'"
          />
          <div
            class="grow md:w-auto w-full min-w-0 flex flex-col justify-center from-primary/15 to-transparent rounded-lg p-8"
            :class="isOdd(i) ? 'bg-gradient-to-r' : 'bg-gradient-to-l'"
            :data-aos="isOdd(i) ? 'fade-right' : 'fade-left'"
          >
            <div>
              <div class="md:text-3xl text-2xl font-bold">
                {{ career.company }}
              </div>
              <div class="text-primary mt-3">{{ career.position }}</div>
              <div class="text-sm">{{ career.date }}</div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>
